name: haiku
version: 1.0.5
homepage: https://github.com/kharland/haiku
description: Detect and create Hiakus from plain text.
author: Kendal Harland <kendaljharland@gmail.com>
dependencies:
  meta:
  packages:
dev_dependencies:
  test:
